substitutions:
  device_name: "BlueTherm"
  sensor_address: "A4:C1:38:EF:8F:C4"

esphome:
  name: blue-thermostat-version1
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "20"
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "541d22ee62e474c7e801886d9c6fd838"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shelly-Test Fallback Hotspot"
    password: "OPbNexvpOhCX"

output:
  - platform: gpio
    id: "LED_output"
    inverted: true
    pin: GPIO0

  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "LED"
    name: "${device_name} LED"
    output: "LED_output"

  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - climate.control:
            id: thermos
            mode: "OFF"
        - switch.turn_on: "relay"
    on_release:
      then:
        - switch.turn_off: "relay"
        - climate.control:
            id: thermos
            mode: "HEAT"
    filters:
      - delayed_on_off: 50ms
  
  - platform: gpio
    name: "${device_name} Button"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - climate.control:
            id: thermos
            mode: "OFF"
        - switch.turn_on: "relay"     
    filters:
      - delayed_on_off: 5ms

esp32_ble_tracker:
  scan_parameters:
    active: false

sensor:
  - platform: atc_mithermometer
    mac_address: "${sensor_address}"
    temperature:
      id: "temp"
      name: "${device_name} Temperature"
    humidity:
      name: "${device_name} Humidity"
    battery_level:
      name: "${device_name} Battery"

climate:
  - platform: thermostat
    id: thermos
    name: "${device_name} Thermostat"
    default_preset: Home
    sensor: temp
    heat_deadband: 0.3
    heat_overrun: 0.3
    min_heating_off_time: 1s
    min_heating_run_time: 1s
    min_idle_time: 1s
    heat_action:
     - switch.turn_on: relay
    idle_action:
     - switch.turn_off: relay
    preset:
      - name: Home
        default_target_temperature_low: 21 
      - name: Away
        default_target_temperature_low: 18
